# Generated by Django 5.1.4 on 2026-04-15 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_slug', models.CharField(max_length=50)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('essential', 'Essential'), ('premium', 'Premium'), ('bulk', 'Bulk')], max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_branding', models.CharField(blank=True, max_length=200)),
                ('custom_text', models.JSONField()),
                ('custom_styling', models.JSONField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=10)),
                ('link_token', models.CharField(max_length=12, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid_cents', models.IntegerField(default=0)),
                ('paddle_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
                'indexes': [models.Index(fields=['link_token'], name='cards_link_to_ce9f21_idx'), models.Index(fields=['expires_at'], name='cards_expires_1d1e47_idx'), models.Index(fields=['scheduled_at'], name='cards_schedul_c2edf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='cards.card')),
            ],
            options={
                'db_table': 'recipients',
                'indexes': [models.Index(fields=['card'], name='recipients_card_id_602628_idx')],
            },
        ),
    ]
