# Generated by Django 5.1.4 on 2026-04-15 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOpen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='cards.card')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opens', to='cards.recipient')),
            ],
            options={
                'db_table': 'card_opens',
                'indexes': [models.Index(fields=['card'], name='card_opens_card_id_a5ab7c_idx'), models.Index(fields=['opened_at'], name='card_opens_opened__114995_idx')],
            },
        ),
    ]
